#ifndef CORE_SHADER_RECOMPILIER_INTERMEDIATEREPRESENTATION_INCLUDE_INTERMEDIATEREPRESENTATION_IROPCODE_HPP
#define CORE_SHADER_RECOMPILIER_INTERMEDIATEREPRESENTATION_INCLUDE_INTERMEDIATEREPRESENTATION_IROPCODE_HPP

#include "IntermediateRepresentation/IrType.hpp"
#include <cstdint>
#include <cstddef>
#include <string_view>

namespace ShaderRecompiler {

enum class IrOpcode : std::uint16_t {
    Identity,
    Phi,
    GetRegister,
    SetRegister,
    IAdd32,
    ISub32,
    IMul32,
    IDiv32,
    IMod32,
    IAnd32,
    IOr32,
    IXor32,
    IShiftLeft32,
    IShiftRightLogical32,
    IShiftRightArithmetic32,
    INegate32,
    INot32,
    FAdd32,
    FSub32,
    FMul32,
    FDiv32,
    FNegate32,
    FAbs32,
    FFma32,
    FSqrt32,
    FRcp32,
    FRsq32,
    FMin32,
    FMax32,
    FFloor32,
    FCeil32,
    FFract32,
    ConvertFToI32,
    ConvertIToF32,
    ConvertFToU32,
    ConvertUToF32,
    CompareEqual,
    CompareNotEqual,
    CompareLessThan,
    CompareGreaterThan,
    Select,
    Branch,
    BranchConditional,
    Loop,
    LoopMerge,
    Return,
    Unreachable,
    LoadBuffer,
    StoreBuffer,
    LoadImage,
    StoreImage,
    ImageSampleImplicitLod,
    ImageSampleExplicitLod,
    LoadShared,
    StoreShared,
    Barrier,
    EmitVertex,
    Discard,
    ReadFirstLane,
    ReadLane,
    Ballot,
    Void,
    Reference,
    ReferenceU32,
    GetUserData,
    GetShaderBase,
    MeshDrawParameter,
    MeshAllocate,
    TessellationBase,
    GetTessellationAttribute,
    SetTessellationAttribute,
    GetBuiltin,
    GetThreadBitScalarRegister,
    SetThreadBitScalarRegister,
    GetScalarMaskTag,
    SetScalarMaskTag,
    GetScalarRegister,
    SetScalarRegister,
    GetVectorRegister,
    SetVectorRegister,
    GetGotoVariable,
    SetGotoVariable,
    GetScc,
    SetScc,
    GetExec,
    SetExec,
    GetExecLo,
    SetExecLo,
    GetExecHi,
    SetExecHi,
    GetVcc,
    SetVcc,
    GetVccLo,
    SetVccLo,
    GetVccHi,
    SetVccHi,
    GetM0,
    SetM0,
    UndefU1,
    UndefU8,
    UndefU16,
    UndefU32,
    UndefU64,
    BitCastU16F16,
    BitCastF16U16,
    BitCastU32F32,
    BitCastF32U32,
    ConvertU16U32,
    ConvertU32U16,
    ConvertU8U32,
    ConvertU32U8,
    ConvertF32F16,
    ConvertF16F32,
    ConvertS32F32,
    ConvertU32F32,
    ConvertF32S32,
    ConvertF32U32,
    CompositeConstructU64,
    CompositeConstructU32x2,
    CompositeConstructU32x3,
    CompositeConstructF32x2,
    CompositeConstructU32x4,
    CompositeExtractU64,
    CompositeExtractU32x2,
    CompositeExtractU32x3,
    CompositeExtractU32x4,
    PackHalf2x16,
    PackSnorm2x16,
    PackUnorm2x16,
    PackFloat2x16Rtz,
    FPAbs32,
    FPNeg32,
    FPSaturate32,
    BitFieldInsert,
    BitFieldUExtract,
    BitFieldSExtract,
    DppMoveU32,
    DppUpdateU32,
    WqmU64,
    SelectU1,
    SelectF32,
    IAdd64,
    IAddCarry32,
    ISub64,
    IMul64,
    UDiv32,
    SMulHi,
    UMulHi,
    IAbs32,
    ShiftLeftLogical32,
    ShiftLeftLogical64,
    ShiftRightLogical32,
    ShiftRightLogical64,
    ShiftRightArithmetic32,
    ShiftRightArithmetic64,
    BitwiseAnd32,
    BitwiseAnd64,
    BitwiseOr32,
    BitwiseXor32,
    BitwiseNot32,
    BitReverse32,
    BitCount32,
    BitCount64,
    FindUMsb32,
    FindUMsb64,
    FindILsb32,
    SMin32,
    UMin32,
    SMax32,
    UMax32,
    SMinTri32,
    UMinTri32,
    SMaxTri32,
    UMaxTri32,
    SMedTri32,
    UMedTri32,
    SLessThan32,
    SLessThan64,
    ULessThan32,
    ULessThan64,
    IEqual32,
    IEqual64,
    SLessThanEqual32,
    ULessThanEqual32,
    SGreaterThan32,
    UGreaterThan32,
    UGreaterThan64,
    INotEqual32,
    INotEqual64,
    SGreaterThanEqual32,
    UGreaterThanEqual32,
    LogicalOr,
    LogicalAnd,
    LogicalXor,
    LogicalNot,
    FPOrdEqual32,
    FPUnordEqual32,
    FPOrdNotEqual32,
    FPUnordNotEqual32,
    FPOrdLessThan32,
    FPUnordLessThan32,
    FPOrdGreaterThan32,
    FPUnordGreaterThan32,
    FPOrdLessThanEqual32,
    FPUnordLessThanEqual32,
    FPOrdGreaterThanEqual32,
    FPUnordGreaterThanEqual32,
    FPIsNan32,
    FPCmpClass32,
    FPAdd32,
    FPSub32,
    FPFma32,
    FPMul32,
    FPMin32,
    FPMax32,
    FPMinTri32,
    FPMaxTri32,
    FPMedTri32,
    FPRecip32,
    FPRecipIFlag32,
    FPRecipSqrt32,
    FPSqrt,
    FPSin,
    FPCos,
    FPExp2,
    FPLog2,
    FPLdexp,
    FPRoundEven32,
    FPFloor32,
    FPCeil32,
    FPTrunc32,
    FPFract32,
    LaneId,
    WriteLane,
    Permlane16U32,
    BpermuteU32,
    GetSrtResource,
    GetBufferResource,
    GetAddressResource,
    GetScratchResource,
    GetImageResource,
    GetSamplerResource,
    MakeImageAddress,
    ReadConst,
    ReadConstBuffer,
    LoadAddressU8,
    LoadAddressU16,
    LoadAddressU32,
    StoreAddressU8,
    StoreAddressU16,
    StoreAddressU32,
    LoadBufferU8,
    LoadBufferU16,
    LoadBufferU32,
    LoadBufferU32x2,
    LoadBufferU32x3,
    LoadBufferU32x4,
    StoreBufferU8,
    StoreBufferU16,
    StoreBufferU32,
    StoreBufferU32x2,
    StoreBufferU32x3,
    StoreBufferU32x4,
    BufferAtomicSwap32,
    BufferAtomicCmpSwap32,
    BufferAtomicSwap64,
    BufferAtomicIAdd32,
    BufferAtomicISub32,
    BufferAtomicSMin32,
    BufferAtomicUMin32,
    BufferAtomicSMax32,
    BufferAtomicUMax32,
    BufferAtomicAnd32,
    BufferAtomicOr32,
    BufferAtomicOr64,
    BufferAtomicXor32,
    BufferAtomicFMin32,
    BufferAtomicFMax32,
    LoadSharedU8,
    LoadSharedU16,
    LoadSharedU32,
    LoadSharedU32x2,
    LoadSharedU32x3,
    LoadSharedU32x4,
    WriteSharedU8,
    WriteSharedU16,
    WriteSharedU32,
    WriteSharedU32x2,
    WriteSharedU32x3,
    WriteSharedU32x4,
    SharedAtomicFMin32,
    SharedAtomicFMax32,
    SharedAtomicSwap32,
    SharedAtomicIAdd32,
    SharedAtomicISub32,
    SharedAtomicInc32,
    SharedAtomicDec32,
    SharedAtomicSMin32,
    SharedAtomicUMin32,
    SharedAtomicSMax32,
    SharedAtomicUMax32,
    SharedAtomicAnd32,
    SharedAtomicOr32,
    SharedAtomicXor32,
    DataAppend,
    DataConsume,
    SwizzleU32,
    ImageQueryDimensions,
    ImageQueryLod,
    ImageRead,
    ImageWrite,
    ImageSampleRaw,
    ImageGatherRaw,
    ImageAtomicSwap32,
    ImageAtomicIAdd32,
    ImageAtomicUMin32,
    ImageAtomicUMax32,
    ImageAtomicAnd32,
    ImageAtomicOr32,
    ImageAtomicXor32,
    GetAttribute,
    GetInterpolationParameter,
    SetAttribute,
    ControlNop,
    Waitcnt,
    Sendmsg,
    TtraceData,
    InstPrefetch,
    SelectU32,
    Count
};

enum class BufferAccess { None, Read, Write, Atomic };
enum class SharedAccess { None, Read, Write, Atomic, Append, Consume };
enum class AddressAccess { None, Read, Write };
enum class ImageAccess { None, Read, Write, Atomic };
enum class ImageResourceClass { None, Sampled, Storage };

struct AddressOpcodeInfo {
    AddressAccess access = AddressAccess::None;
    std::uint32_t dataBits = 0;
};

struct ImageOpcodeInfo {
    ImageAccess access = ImageAccess::None;
    ImageResourceClass resourceClass = ImageResourceClass::None;
    bool needsSampler = false;
};

struct DppMoveFlags {
    std::uint16_t control = 0;
    std::uint8_t rowMask = 0xf;
    std::uint8_t bankMask = 0xf;
    bool fetchInactive = false;
    bool boundControl = false;
};

struct PermlaneFlags {
    bool x16 = false;
    bool fetchInactive = false;
    bool boundControl = false;
};

struct MemoryFlags {
    std::uint32_t index = 0;
    std::uint32_t pc = 0;
};

struct ExportFlags {
    std::uint32_t index = 0;
    std::uint32_t pc = 0;
};

[[nodiscard]] std::size_t IrOpcodeOperandCount(IrOpcode opcode);

[[nodiscard]] IrType IrOpcodeType(IrOpcode opcode);
[[nodiscard]] IrType IrOpcodeArgumentType(IrOpcode opcode, std::size_t index);
[[nodiscard]] bool IrOpcodeHasSideEffects(IrOpcode opcode);
[[nodiscard]] BufferAccess BufferAccessOf(IrOpcode opcode);
[[nodiscard]] std::uint32_t BufferComponentCount(IrOpcode opcode);
[[nodiscard]] SharedAccess SharedAccessOf(IrOpcode opcode);
[[nodiscard]] std::uint32_t SharedComponentCount(IrOpcode opcode);
[[nodiscard]] AddressOpcodeInfo AddressOpcodeInfoOf(IrOpcode opcode);
[[nodiscard]] ImageOpcodeInfo ImageOpcodeInfoOf(IrOpcode opcode);
[[nodiscard]] std::string_view IrOpcodeName(IrOpcode opcode);

}

#endif
