#ifndef CORE_SHADER_RECOMPILIER_SPIRVBACKEND_INCLUDE_SPIRVBACKEND_SPIRVEMITTERINSTRUCTIONS_HPP
#define CORE_SHADER_RECOMPILIER_SPIRVBACKEND_INCLUDE_SPIRVBACKEND_SPIRVEMITTERINSTRUCTIONS_HPP

#include "SpirvBackend/SpirvEmitterHelpers.hpp"

namespace ShaderRecompiler {

std::uint32_t EmitConvertU16U32(SpirvEmitterState& state, std::uint32_t arg0);
std::uint32_t EmitConvertU8U32(SpirvEmitterState& state, std::uint32_t arg0);
std::uint32_t EmitConvertF16F32(SpirvEmitterState& state, std::uint32_t arg0);
std::uint32_t EmitConvertS32F32(SpirvEmitterState& state, std::uint32_t arg0);
std::uint32_t EmitConvertU32F32(SpirvEmitterState& state, std::uint32_t arg0);
std::uint32_t EmitConvertF32S32(SpirvEmitterState& state, std::uint32_t arg0);
std::uint32_t EmitCompositeExtractU64(SpirvEmitterState& state, std::uint32_t arg0, const IrValue* arg1);
std::uint32_t EmitPackFloat2x16Rtz(SpirvEmitterState& state, std::uint32_t arg0, std::uint32_t arg1);
std::uint32_t EmitFPSaturate32(SpirvEmitterState& state, std::uint32_t arg0);
std::uint32_t EmitIAdd64(SpirvEmitterState& state, std::uint32_t arg0, std::uint32_t arg1);
std::uint32_t EmitISub64(SpirvEmitterState& state, std::uint32_t arg0, std::uint32_t arg1);
std::uint32_t EmitIMul64(SpirvEmitterState& state, std::uint32_t arg0, std::uint32_t arg1);
std::uint32_t EmitSMulHi(SpirvEmitterState& state, std::uint32_t arg0, std::uint32_t arg1);
std::uint32_t EmitUMulHi(SpirvEmitterState& state, std::uint32_t arg0, std::uint32_t arg1);
std::uint32_t EmitIAbs32(SpirvEmitterState& state, std::uint32_t arg0);
std::uint32_t EmitShiftLeftLogical64(SpirvValueEmitContext& ctx, std::uint32_t arg0, const IrValue* arg1);
std::uint32_t EmitShiftRightLogical64(SpirvValueEmitContext& ctx, std::uint32_t arg0, const IrValue* arg1);
std::uint32_t EmitShiftRightArithmetic64(SpirvValueEmitContext& ctx, std::uint32_t arg0, const IrValue* arg1);
std::uint32_t EmitBitwiseAnd64(SpirvEmitterState& state, std::uint32_t arg0, std::uint32_t arg1);
std::uint32_t EmitBitCount64(SpirvEmitterState& state, std::uint32_t arg0);
std::uint32_t EmitFindILsb32(SpirvEmitterState& state, std::uint32_t arg0);
std::uint32_t EmitFindUMsb32(SpirvEmitterState& state, std::uint32_t arg0);
std::uint32_t EmitFindUMsb64(SpirvEmitterState& state, std::uint32_t arg0);
std::uint32_t EmitSMin32(SpirvEmitterState& state, std::uint32_t arg0, std::uint32_t arg1);
std::uint32_t EmitSMax32(SpirvEmitterState& state, std::uint32_t arg0, std::uint32_t arg1);
std::uint32_t EmitUMin32(SpirvEmitterState& state, std::uint32_t arg0, std::uint32_t arg1);
std::uint32_t EmitUMax32(SpirvEmitterState& state, std::uint32_t arg0, std::uint32_t arg1);
std::uint32_t EmitSMinTri32(SpirvEmitterState& state, std::uint32_t arg0, std::uint32_t arg1, std::uint32_t arg2);
std::uint32_t EmitSMaxTri32(SpirvEmitterState& state, std::uint32_t arg0, std::uint32_t arg1, std::uint32_t arg2);
std::uint32_t EmitUMinTri32(SpirvEmitterState& state, std::uint32_t arg0, std::uint32_t arg1, std::uint32_t arg2);
std::uint32_t EmitUMaxTri32(SpirvEmitterState& state, std::uint32_t arg0, std::uint32_t arg1, std::uint32_t arg2);
std::uint32_t EmitSMedTri32(SpirvEmitterState& state, std::uint32_t arg0, std::uint32_t arg1, std::uint32_t arg2);
std::uint32_t EmitUMedTri32(SpirvEmitterState& state, std::uint32_t arg0, std::uint32_t arg1, std::uint32_t arg2);
std::uint32_t EmitIEqual64(SpirvEmitterState& state, std::uint32_t arg0, std::uint32_t arg1);
std::uint32_t EmitINotEqual64(SpirvEmitterState& state, std::uint32_t arg0, std::uint32_t arg1);
std::uint32_t EmitULessThan64(SpirvEmitterState& state, std::uint32_t arg0, std::uint32_t arg1);
std::uint32_t EmitSLessThan64(SpirvEmitterState& state, std::uint32_t arg0, std::uint32_t arg1);
std::uint32_t EmitUGreaterThan64(SpirvEmitterState& state, std::uint32_t arg0, std::uint32_t arg1);
std::uint32_t EmitFPIsNan32(SpirvEmitterState& state, std::uint32_t arg0);
std::uint32_t EmitFPMin32(SpirvEmitterState& state, std::uint32_t arg0, std::uint32_t arg1);
std::uint32_t EmitFPMax32(SpirvEmitterState& state, std::uint32_t arg0, std::uint32_t arg1);
std::uint32_t EmitFPMinTri32(SpirvEmitterState& state, std::uint32_t arg0, std::uint32_t arg1, std::uint32_t arg2);
std::uint32_t EmitFPMaxTri32(SpirvEmitterState& state, std::uint32_t arg0, std::uint32_t arg1, std::uint32_t arg2);
std::uint32_t EmitFPMedTri32(SpirvEmitterState& state, std::uint32_t arg0, std::uint32_t arg1, std::uint32_t arg2);
std::uint32_t EmitFPRecip32(SpirvEmitterState& state, std::uint32_t arg0);
std::uint32_t EmitFPRecipIFlag32(SpirvEmitterState& state, std::uint32_t arg0);
std::uint32_t EmitFPRecipSqrt32(SpirvEmitterState& state, std::uint32_t arg0);
std::uint32_t EmitFPSqrt(SpirvEmitterState& state, std::uint32_t arg0);
std::uint32_t EmitFPExp2(SpirvEmitterState& state, std::uint32_t arg0);
std::uint32_t EmitFPLog2(SpirvEmitterState& state, std::uint32_t arg0);
std::uint32_t EmitFPLdexp(SpirvEmitterState& state, std::uint32_t arg0, std::uint32_t arg1);
std::uint32_t EmitFPSin(SpirvEmitterState& state, std::uint32_t arg0);
std::uint32_t EmitFPCos(SpirvEmitterState& state, std::uint32_t arg0);
std::uint32_t EmitIdentity(SpirvValueEmitContext& ctx, std::uint32_t value);
void EmitVoid(SpirvValueEmitContext& context);
void EmitBarrier(SpirvEmitterState& state);
std::uint32_t EmitMeshDrawParameter(SpirvValueEmitContext& ctx, const IrValue& inst);
std::uint32_t EmitGetTessellationAttribute(SpirvValueEmitContext& ctx, const IrValue& inst);
void EmitSetTessellationAttribute(SpirvValueEmitContext& ctx, const IrValue& inst);
std::uint32_t EmitGetUserData(SpirvEmitterState& state, ScalarReg reg);
std::uint32_t EmitGetBuiltin(SpirvValueEmitContext& ctx, const IrValue* kind, const IrValue* index);
std::uint32_t EmitUndefU1(SpirvEmitterState& state, const IrValue& inst);
std::uint32_t EmitDppMoveU32(SpirvValueEmitContext& ctx, const IrValue& inst);
std::uint32_t EmitDppUpdateU32(SpirvValueEmitContext& ctx, const IrValue& inst);
std::uint32_t EmitWqmU64(SpirvEmitterState& state, std::uint32_t value);
std::uint32_t EmitLaneId(SpirvEmitterState& state);
std::uint32_t EmitBallot(SpirvValueEmitContext& ctx, const IrValue* predicate);
std::uint32_t EmitReadFirstLane(SpirvValueEmitContext& ctx, const IrValue& inst);
std::uint32_t EmitReadLane(SpirvValueEmitContext& ctx, const IrValue& inst);
std::uint32_t EmitWriteLane(SpirvValueEmitContext& ctx, const IrValue& inst);
std::uint32_t EmitPermlane16U32(SpirvValueEmitContext& ctx, const IrValue& inst);
std::uint32_t EmitGetAttribute(SpirvValueEmitContext& ctx, const IrValue& inst);
std::uint32_t EmitGetInterpolationParameter(SpirvValueEmitContext& ctx, const IrValue& inst);
void EmitSetAttribute(SpirvValueEmitContext& ctx, const IrValue& inst);
std::uint32_t EmitGetShaderBase(SpirvValueEmitContext& ctx);
void EmitLoadMemory(SpirvValueEmitContext& ctx, const IrValue& inst);
void EmitStoreMemory(SpirvValueEmitContext& ctx, const IrValue& inst);
std::uint32_t EmitAtomic32(SpirvValueEmitContext& ctx, const IrValue& inst);
std::uint32_t EmitBufferAtomic64(SpirvValueEmitContext& ctx, const IrValue& inst);
std::uint32_t EmitBufferFloatAtomic(SpirvValueEmitContext& ctx, const IrValue& inst);
void EmitSharedFloatAtomic(SpirvValueEmitContext& ctx, const IrValue& inst);
std::uint32_t EmitSharedIncDec(SpirvValueEmitContext& ctx, const IrValue& inst);
std::uint32_t EmitAppendConsume(SpirvValueEmitContext& ctx, const IrValue& inst);
std::uint32_t EmitBpermuteU32(SpirvValueEmitContext& ctx, const IrValue& inst);
std::uint32_t EmitReadConst(SpirvValueEmitContext& ctx, const IrValue& inst);
void EmitReadConstBuffer(SpirvValueEmitContext& ctx, const IrValue& inst);
std::uint32_t EmitSwizzleU32(SpirvValueEmitContext& ctx, const IrValue& inst);
void EmitImage(SpirvValueEmitContext& ctx, const IrValue& inst);
void EmitUnreachable(SpirvValueEmitContext& ctx, const IrValue& inst);
std::uint32_t EmitBitCastU16F16(SpirvEmitterState& state, std::uint32_t arg0);
std::uint32_t EmitBitCastF32U32(SpirvEmitterState& state, std::uint32_t arg0);
std::uint32_t EmitConvertF32U32(SpirvEmitterState& state, std::uint32_t arg0);
std::uint32_t EmitCompositeConstructU64(SpirvEmitterState& state, std::uint32_t arg0, std::uint32_t arg1);
std::uint32_t EmitCompositeConstructU32x2(SpirvEmitterState& state, std::uint32_t arg0, std::uint32_t arg1);
std::uint32_t EmitCompositeConstructU32x3(SpirvEmitterState& state, std::uint32_t arg0, std::uint32_t arg1, std::uint32_t arg2);
std::uint32_t EmitCompositeConstructF32x2(SpirvEmitterState& state, std::uint32_t arg0, std::uint32_t arg1);
std::uint32_t EmitCompositeConstructU32x4(SpirvEmitterState& state, std::uint32_t arg0, std::uint32_t arg1, std::uint32_t arg2, std::uint32_t arg3);
std::uint32_t EmitBitFieldInsert(SpirvEmitterState& state, std::uint32_t arg0, std::uint32_t arg1, std::uint32_t arg2, std::uint32_t arg3);
std::uint32_t EmitBitFieldUExtract(SpirvEmitterState& state, std::uint32_t arg0, std::uint32_t arg1, std::uint32_t arg2);
std::uint32_t EmitBitFieldSExtract(SpirvEmitterState& state, std::uint32_t arg0, std::uint32_t arg1, std::uint32_t arg2);
std::uint32_t EmitSelectU1(SpirvEmitterState& state, std::uint32_t arg0, std::uint32_t arg1, std::uint32_t arg2);
std::uint32_t EmitSelectU32(SpirvEmitterState& state, std::uint32_t arg0, std::uint32_t arg1, std::uint32_t arg2);
std::uint32_t EmitSelectF32(SpirvEmitterState& state, std::uint32_t arg0, std::uint32_t arg1, std::uint32_t arg2);
std::uint32_t EmitIAdd32(SpirvEmitterState& state, std::uint32_t arg0, std::uint32_t arg1);
std::uint32_t EmitISub32(SpirvEmitterState& state, std::uint32_t arg0, std::uint32_t arg1);
std::uint32_t EmitIMul32(SpirvEmitterState& state, std::uint32_t arg0, std::uint32_t arg1);
std::uint32_t EmitUDiv32(SpirvEmitterState& state, std::uint32_t arg0, std::uint32_t arg1);
std::uint32_t EmitIAddCarry32(SpirvEmitterState& state, std::uint32_t arg0, std::uint32_t arg1);
std::uint32_t EmitShiftLeftLogical32(SpirvEmitterState& state, std::uint32_t arg0, std::uint32_t arg1);
std::uint32_t EmitShiftRightLogical32(SpirvEmitterState& state, std::uint32_t arg0, std::uint32_t arg1);
std::uint32_t EmitShiftRightArithmetic32(SpirvEmitterState& state, std::uint32_t arg0, std::uint32_t arg1);
std::uint32_t EmitBitwiseAnd32(SpirvEmitterState& state, std::uint32_t arg0, std::uint32_t arg1);
std::uint32_t EmitBitwiseOr32(SpirvEmitterState& state, std::uint32_t arg0, std::uint32_t arg1);
std::uint32_t EmitBitwiseXor32(SpirvEmitterState& state, std::uint32_t arg0, std::uint32_t arg1);
std::uint32_t EmitBitwiseNot32(SpirvEmitterState& state, std::uint32_t arg0);
std::uint32_t EmitBitReverse32(SpirvEmitterState& state, std::uint32_t arg0);
std::uint32_t EmitBitCount32(SpirvEmitterState& state, std::uint32_t arg0);
std::uint32_t EmitSLessThan32(SpirvEmitterState& state, std::uint32_t arg0, std::uint32_t arg1);
std::uint32_t EmitULessThan32(SpirvEmitterState& state, std::uint32_t arg0, std::uint32_t arg1);
std::uint32_t EmitIEqual32(SpirvEmitterState& state, std::uint32_t arg0, std::uint32_t arg1);
std::uint32_t EmitSLessThanEqual32(SpirvEmitterState& state, std::uint32_t arg0, std::uint32_t arg1);
std::uint32_t EmitULessThanEqual32(SpirvEmitterState& state, std::uint32_t arg0, std::uint32_t arg1);
std::uint32_t EmitSGreaterThan32(SpirvEmitterState& state, std::uint32_t arg0, std::uint32_t arg1);
std::uint32_t EmitUGreaterThan32(SpirvEmitterState& state, std::uint32_t arg0, std::uint32_t arg1);
std::uint32_t EmitINotEqual32(SpirvEmitterState& state, std::uint32_t arg0, std::uint32_t arg1);
std::uint32_t EmitSGreaterThanEqual32(SpirvEmitterState& state, std::uint32_t arg0, std::uint32_t arg1);
std::uint32_t EmitUGreaterThanEqual32(SpirvEmitterState& state, std::uint32_t arg0, std::uint32_t arg1);
std::uint32_t EmitLogicalOr(SpirvEmitterState& state, std::uint32_t arg0, std::uint32_t arg1);
std::uint32_t EmitLogicalAnd(SpirvEmitterState& state, std::uint32_t arg0, std::uint32_t arg1);
std::uint32_t EmitLogicalXor(SpirvEmitterState& state, std::uint32_t arg0, std::uint32_t arg1);
std::uint32_t EmitLogicalNot(SpirvEmitterState& state, std::uint32_t arg0);
std::uint32_t EmitFPOrdEqual32(SpirvEmitterState& state, std::uint32_t arg0, std::uint32_t arg1);
std::uint32_t EmitFPUnordEqual32(SpirvEmitterState& state, std::uint32_t arg0, std::uint32_t arg1);
std::uint32_t EmitFPOrdNotEqual32(SpirvEmitterState& state, std::uint32_t arg0, std::uint32_t arg1);
std::uint32_t EmitFPUnordNotEqual32(SpirvEmitterState& state, std::uint32_t arg0, std::uint32_t arg1);
std::uint32_t EmitFPOrdLessThan32(SpirvEmitterState& state, std::uint32_t arg0, std::uint32_t arg1);
std::uint32_t EmitFPUnordLessThan32(SpirvEmitterState& state, std::uint32_t arg0, std::uint32_t arg1);
std::uint32_t EmitFPOrdGreaterThan32(SpirvEmitterState& state, std::uint32_t arg0, std::uint32_t arg1);
std::uint32_t EmitFPUnordGreaterThan32(SpirvEmitterState& state, std::uint32_t arg0, std::uint32_t arg1);
std::uint32_t EmitFPOrdLessThanEqual32(SpirvEmitterState& state, std::uint32_t arg0, std::uint32_t arg1);
std::uint32_t EmitFPUnordLessThanEqual32(SpirvEmitterState& state, std::uint32_t arg0, std::uint32_t arg1);
std::uint32_t EmitFPOrdGreaterThanEqual32(SpirvEmitterState& state, std::uint32_t arg0, std::uint32_t arg1);
std::uint32_t EmitFPUnordGreaterThanEqual32(SpirvEmitterState& state, std::uint32_t arg0, std::uint32_t arg1);
std::uint32_t EmitFPAdd32(SpirvEmitterState& state, std::uint32_t arg0, std::uint32_t arg1);
std::uint32_t EmitFPSub32(SpirvEmitterState& state, std::uint32_t arg0, std::uint32_t arg1);
std::uint32_t EmitFPMul32(SpirvEmitterState& state, std::uint32_t arg0, std::uint32_t arg1);
std::uint32_t EmitAddU32(SpirvEmitterState& state, std::uint32_t arg0, std::uint32_t arg1);
std::uint32_t EmitTBufferSelectF32(SpirvEmitterState& state, std::uint32_t arg0, std::uint32_t arg1, std::uint32_t arg2);
std::uint32_t EmitSelectValueU32(SpirvEmitterState& state, std::uint32_t arg0, std::uint32_t arg1, std::uint32_t arg2);
std::uint32_t EmitOrU32(SpirvEmitterState& state, std::uint32_t arg0, std::uint32_t arg1);
std::uint32_t EmitBitcastF32ToU32(SpirvEmitterState& state, std::uint32_t arg0);
std::uint32_t EmitBitcastU32ToF32(SpirvEmitterState& state, std::uint32_t arg0);
std::uint32_t EmitAndU32(SpirvEmitterState& state, std::uint32_t arg0, std::uint32_t arg1);
std::uint32_t EmitLogicalAndBool(SpirvEmitterState& state, std::uint32_t arg0, std::uint32_t arg1);
std::uint32_t EmitLogicalOrBool(SpirvEmitterState& state, std::uint32_t arg0, std::uint32_t arg1);
std::uint32_t EmitLogicalNotBool(SpirvEmitterState& state, std::uint32_t arg0);
std::uint32_t EmitTruncF32Value(SpirvEmitterState& state, std::uint32_t arg0);
std::uint32_t EmitFNegateValue(SpirvEmitterState& state, std::uint32_t arg0);
std::uint32_t EmitFAbsValue(SpirvEmitterState& state, std::uint32_t arg0);
std::uint32_t EmitPackHalf2x16(SpirvEmitterState& state, std::uint32_t arg0);
std::uint32_t EmitPackSnorm2x16(SpirvEmitterState& state, std::uint32_t arg0);
std::uint32_t EmitPackUnorm2x16(SpirvEmitterState& state, std::uint32_t arg0);
std::uint32_t EmitFPFma32(SpirvEmitterState& state, std::uint32_t arg0, std::uint32_t arg1, std::uint32_t arg2);
std::uint32_t EmitFPRoundEven32(SpirvEmitterState& state, std::uint32_t arg0);
std::uint32_t EmitFPFloor32(SpirvEmitterState& state, std::uint32_t arg0);
std::uint32_t EmitFPCeil32(SpirvEmitterState& state, std::uint32_t arg0);
std::uint32_t EmitFPTrunc32(SpirvEmitterState& state, std::uint32_t arg0);
std::uint32_t EmitFPFract32(SpirvEmitterState& state, std::uint32_t arg0);
std::uint32_t EmitBitCastF16U16(SpirvEmitterState& state, std::uint32_t arg0);
std::uint32_t EmitConvertU32U16(SpirvEmitterState& state, std::uint32_t arg0);
std::uint32_t EmitConvertU32U8(SpirvEmitterState& state, std::uint32_t arg0);
std::uint32_t EmitBitCastU32F32(SpirvEmitterState& state, std::uint32_t arg0);
std::uint32_t EmitConvertF32F16(SpirvEmitterState& state, std::uint32_t bits);
std::uint32_t EmitCompositeExtractU32x2(SpirvEmitterState& state, std::uint32_t arg0, const IrValue* arg1);
std::uint32_t EmitCompositeExtractU32x3(SpirvEmitterState& state, std::uint32_t arg0, const IrValue* arg1);
std::uint32_t EmitCompositeExtractU32x4(SpirvEmitterState& state, std::uint32_t arg0, const IrValue* arg1);
std::uint32_t EmitFPAbs32(SpirvEmitterState& state, std::uint32_t arg0);
std::uint32_t EmitFPNeg32(SpirvEmitterState& state, std::uint32_t arg0);
std::uint32_t EmitFPCmpClass32(SpirvEmitterState& state, std::uint32_t value, std::uint32_t mask);
void EmitReference(SpirvValueEmitContext& context);
void EmitReferenceU32(SpirvValueEmitContext& context);
void EmitControlNop(SpirvValueEmitContext& context);
void EmitWaitcnt(SpirvValueEmitContext& context);
void EmitSendmsg(SpirvValueEmitContext& context);
void EmitTtraceData(SpirvValueEmitContext& context);
void EmitInstPrefetch(SpirvValueEmitContext& context);
std::uint32_t EmitUndefU8(SpirvEmitterState& state, const IrValue& inst);
std::uint32_t EmitUndefU16(SpirvEmitterState& state, const IrValue& inst);
std::uint32_t EmitUndefU32(SpirvEmitterState& state, const IrValue& inst);
std::uint32_t EmitUndefU64(SpirvEmitterState& state, const IrValue& inst);
void EmitGetSrtResource(SpirvValueEmitContext& context);
void EmitGetBufferResource(SpirvValueEmitContext& context);
void EmitGetAddressResource(SpirvValueEmitContext& context);
void EmitGetScratchResource(SpirvValueEmitContext& context);
void EmitGetImageResource(SpirvValueEmitContext& context);
void EmitGetSamplerResource(SpirvValueEmitContext& context);
void EmitMakeImageAddress(SpirvValueEmitContext& context);
void EmitLoadAddressU8(SpirvValueEmitContext& ctx, const IrValue& inst);
void EmitLoadAddressU16(SpirvValueEmitContext& ctx, const IrValue& inst);
void EmitLoadAddressU32(SpirvValueEmitContext& ctx, const IrValue& inst);
void EmitStoreAddressU8(SpirvValueEmitContext& ctx, const IrValue& inst);
void EmitStoreAddressU16(SpirvValueEmitContext& ctx, const IrValue& inst);
void EmitStoreAddressU32(SpirvValueEmitContext& ctx, const IrValue& inst);
void EmitLoadBufferU8(SpirvValueEmitContext& ctx, const IrValue& inst);
void EmitLoadBufferU16(SpirvValueEmitContext& ctx, const IrValue& inst);
void EmitLoadBufferU32(SpirvValueEmitContext& ctx, const IrValue& inst);
void EmitLoadBufferU32x2(SpirvValueEmitContext& ctx, const IrValue& inst);
void EmitLoadBufferU32x3(SpirvValueEmitContext& ctx, const IrValue& inst);
void EmitLoadBufferU32x4(SpirvValueEmitContext& ctx, const IrValue& inst);
void EmitStoreBufferU8(SpirvValueEmitContext& ctx, const IrValue& inst);
void EmitStoreBufferU16(SpirvValueEmitContext& ctx, const IrValue& inst);
void EmitStoreBufferU32(SpirvValueEmitContext& ctx, const IrValue& inst);
void EmitStoreBufferU32x2(SpirvValueEmitContext& ctx, const IrValue& inst);
void EmitStoreBufferU32x3(SpirvValueEmitContext& ctx, const IrValue& inst);
void EmitStoreBufferU32x4(SpirvValueEmitContext& ctx, const IrValue& inst);
std::uint32_t EmitBufferAtomicSwap32(SpirvValueEmitContext& ctx, const IrValue& inst);
std::uint32_t EmitBufferAtomicCmpSwap32(SpirvValueEmitContext& ctx, const IrValue& inst);
std::uint32_t EmitBufferAtomicSwap64(SpirvValueEmitContext& ctx, const IrValue& inst);
std::uint32_t EmitBufferAtomicIAdd32(SpirvValueEmitContext& ctx, const IrValue& inst);
std::uint32_t EmitBufferAtomicISub32(SpirvValueEmitContext& ctx, const IrValue& inst);
std::uint32_t EmitBufferAtomicSMin32(SpirvValueEmitContext& ctx, const IrValue& inst);
std::uint32_t EmitBufferAtomicUMin32(SpirvValueEmitContext& ctx, const IrValue& inst);
std::uint32_t EmitBufferAtomicSMax32(SpirvValueEmitContext& ctx, const IrValue& inst);
std::uint32_t EmitBufferAtomicUMax32(SpirvValueEmitContext& ctx, const IrValue& inst);
std::uint32_t EmitBufferAtomicAnd32(SpirvValueEmitContext& ctx, const IrValue& inst);
std::uint32_t EmitBufferAtomicOr32(SpirvValueEmitContext& ctx, const IrValue& inst);
std::uint32_t EmitBufferAtomicOr64(SpirvValueEmitContext& ctx, const IrValue& inst);
std::uint32_t EmitBufferAtomicXor32(SpirvValueEmitContext& ctx, const IrValue& inst);
std::uint32_t EmitBufferAtomicFMin32(SpirvValueEmitContext& ctx, const IrValue& inst);
std::uint32_t EmitBufferAtomicFMax32(SpirvValueEmitContext& ctx, const IrValue& inst);
void EmitLoadSharedU8(SpirvValueEmitContext& ctx, const IrValue& inst);
void EmitLoadSharedU16(SpirvValueEmitContext& ctx, const IrValue& inst);
void EmitLoadSharedU32(SpirvValueEmitContext& ctx, const IrValue& inst);
void EmitLoadSharedU32x2(SpirvValueEmitContext& ctx, const IrValue& inst);
void EmitLoadSharedU32x3(SpirvValueEmitContext& ctx, const IrValue& inst);
void EmitLoadSharedU32x4(SpirvValueEmitContext& ctx, const IrValue& inst);
void EmitWriteSharedU8(SpirvValueEmitContext& ctx, const IrValue& inst);
void EmitWriteSharedU16(SpirvValueEmitContext& ctx, const IrValue& inst);
void EmitWriteSharedU32(SpirvValueEmitContext& ctx, const IrValue& inst);
void EmitWriteSharedU32x2(SpirvValueEmitContext& ctx, const IrValue& inst);
void EmitWriteSharedU32x3(SpirvValueEmitContext& ctx, const IrValue& inst);
void EmitWriteSharedU32x4(SpirvValueEmitContext& ctx, const IrValue& inst);
void EmitSharedAtomicFMin32(SpirvValueEmitContext& ctx, const IrValue& inst);
void EmitSharedAtomicFMax32(SpirvValueEmitContext& ctx, const IrValue& inst);
std::uint32_t EmitSharedAtomicSwap32(SpirvValueEmitContext& ctx, const IrValue& inst);
std::uint32_t EmitSharedAtomicIAdd32(SpirvValueEmitContext& ctx, const IrValue& inst);
std::uint32_t EmitSharedAtomicISub32(SpirvValueEmitContext& ctx, const IrValue& inst);
std::uint32_t EmitSharedAtomicInc32(SpirvValueEmitContext& ctx, const IrValue& inst);
std::uint32_t EmitSharedAtomicDec32(SpirvValueEmitContext& ctx, const IrValue& inst);
std::uint32_t EmitSharedAtomicSMin32(SpirvValueEmitContext& ctx, const IrValue& inst);
std::uint32_t EmitSharedAtomicUMin32(SpirvValueEmitContext& ctx, const IrValue& inst);
std::uint32_t EmitSharedAtomicSMax32(SpirvValueEmitContext& ctx, const IrValue& inst);
std::uint32_t EmitSharedAtomicUMax32(SpirvValueEmitContext& ctx, const IrValue& inst);
std::uint32_t EmitSharedAtomicAnd32(SpirvValueEmitContext& ctx, const IrValue& inst);
std::uint32_t EmitSharedAtomicOr32(SpirvValueEmitContext& ctx, const IrValue& inst);
std::uint32_t EmitSharedAtomicXor32(SpirvValueEmitContext& ctx, const IrValue& inst);
std::uint32_t EmitDataAppend(SpirvValueEmitContext& ctx, const IrValue& inst);
std::uint32_t EmitDataConsume(SpirvValueEmitContext& ctx, const IrValue& inst);
void EmitImageQueryDimensions(SpirvValueEmitContext& ctx, const IrValue& inst);
void EmitImageQueryLod(SpirvValueEmitContext& ctx, const IrValue& inst);
void EmitImageRead(SpirvValueEmitContext& ctx, const IrValue& inst);
void EmitImageWrite(SpirvValueEmitContext& ctx, const IrValue& inst);
void EmitImageSampleRaw(SpirvValueEmitContext& ctx, const IrValue& inst);
void EmitImageGatherRaw(SpirvValueEmitContext& ctx, const IrValue& inst);
void EmitImageAtomicSwap32(SpirvValueEmitContext& ctx, const IrValue& inst);
void EmitImageAtomicIAdd32(SpirvValueEmitContext& ctx, const IrValue& inst);
void EmitImageAtomicUMin32(SpirvValueEmitContext& ctx, const IrValue& inst);
void EmitImageAtomicUMax32(SpirvValueEmitContext& ctx, const IrValue& inst);
void EmitImageAtomicAnd32(SpirvValueEmitContext& ctx, const IrValue& inst);
void EmitImageAtomicOr32(SpirvValueEmitContext& ctx, const IrValue& inst);
void EmitImageAtomicXor32(SpirvValueEmitContext& ctx, const IrValue& inst);
void EmitPhi(SpirvValueEmitContext& ctx, const IrValue& inst);
void EmitTessellationBase(SpirvValueEmitContext& ctx, const IrValue& inst);
void EmitGetThreadBitScalarRegister(SpirvValueEmitContext& ctx, const IrValue& inst);
void EmitSetThreadBitScalarRegister(SpirvValueEmitContext& ctx, const IrValue& inst);
void EmitGetScalarMaskTag(SpirvValueEmitContext& ctx, const IrValue& inst);
void EmitSetScalarMaskTag(SpirvValueEmitContext& ctx, const IrValue& inst);
void EmitGetScalarRegister(SpirvValueEmitContext& ctx, const IrValue& inst);
void EmitSetScalarRegister(SpirvValueEmitContext& ctx, const IrValue& inst);
void EmitGetVectorRegister(SpirvValueEmitContext& ctx, const IrValue& inst);
void EmitSetVectorRegister(SpirvValueEmitContext& ctx, const IrValue& inst);
void EmitGetGotoVariable(SpirvValueEmitContext& ctx, const IrValue& inst);
void EmitSetGotoVariable(SpirvValueEmitContext& ctx, const IrValue& inst);
void EmitGetScc(SpirvValueEmitContext& ctx, const IrValue& inst);
void EmitSetScc(SpirvValueEmitContext& ctx, const IrValue& inst);
void EmitGetExec(SpirvValueEmitContext& ctx, const IrValue& inst);
void EmitSetExec(SpirvValueEmitContext& ctx, const IrValue& inst);
void EmitGetExecLo(SpirvValueEmitContext& ctx, const IrValue& inst);
void EmitSetExecLo(SpirvValueEmitContext& ctx, const IrValue& inst);
void EmitGetExecHi(SpirvValueEmitContext& ctx, const IrValue& inst);
void EmitSetExecHi(SpirvValueEmitContext& ctx, const IrValue& inst);
void EmitGetVcc(SpirvValueEmitContext& ctx, const IrValue& inst);
void EmitSetVcc(SpirvValueEmitContext& ctx, const IrValue& inst);
void EmitGetVccLo(SpirvValueEmitContext& ctx, const IrValue& inst);
void EmitSetVccLo(SpirvValueEmitContext& ctx, const IrValue& inst);
void EmitGetVccHi(SpirvValueEmitContext& ctx, const IrValue& inst);
void EmitSetVccHi(SpirvValueEmitContext& ctx, const IrValue& inst);
void EmitGetM0(SpirvValueEmitContext& ctx, const IrValue& inst);
void EmitSetM0(SpirvValueEmitContext& ctx, const IrValue& inst);

}

#endif
