#ifndef CORE_LIBS_PRX_LIBSCEPAD_PAD_HPP
#define CORE_LIBS_PRX_LIBSCEPAD_PAD_HPP

constexpr int PAD_OK = 0;
constexpr int PAD_ERROR_INVALID_ARG = -2137915390;
constexpr int PAD_ERROR_INVALID_HANDLE = -2137915384;

constexpr int PAD_PORT_TYPE_STANDARD = 0;
constexpr int PAD_PORT_TYPE_SPECIAL = 2;
constexpr int PAD_PORT_TYPE_REMOTE = 16;
constexpr int PAD_USER_ID_SYSTEM = 0xff;
constexpr int PAD_HANDLE = 1;
constexpr int PAD_MAX_SLOTS = 4;
constexpr int PAD_ERROR_ALREADY_OPENED = -2137915389;
constexpr int PAD_ERROR_NOT_INITIALIZED = -2137915388;
constexpr int PAD_ERROR_RESOURCE_ALLOCATION_FAILED = -2137915387;

constexpr int PAD_CONNECTION_TYPE_LOCAL = 0;
constexpr int PAD_DEVICE_CLASS_STANDARD = 0;

#endif

