#ifndef CORE_LIBS_PRX_LIBSCENPUNIVERSALDATASYSTEM_NPUNIVERSALDATASYSTEM_HPP
#define CORE_LIBS_PRX_LIBSCENPUNIVERSALDATASYSTEM_NPUNIVERSALDATASYSTEM_HPP

#include <cstddef>
#include <cstdint>

#include "SceTypes.hpp"

static constexpr int SCE_NP_UNIVERSAL_DATA_SYSTEM_OK = 0;
static constexpr int SCE_NP_UNIVERSAL_DATA_SYSTEM_ERROR_INVALID_ARGUMENT = -2141900542;

static constexpr int NP_UNIVERSAL_DATA_SYSTEM_CONTEXT_DEFAULT = 1;
static constexpr int NP_UNIVERSAL_DATA_SYSTEM_HANDLE_DEFAULT  = 1;

static constexpr const char* NP_UNIVERSAL_DATA_SYSTEM_EMPTY_JSON = "{}";
static constexpr size_t NP_UNIVERSAL_DATA_SYSTEM_EMPTY_EVENT_SIZE = 3;

#endif
